[package]
name = "fxbenchmark"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "^0.8"
rustc-hash = "^1.1"

[dev-dependencies]
criterion = "^0.5"

[[bench]]
name = "hash_bench"
harness = false
